<?php

declare(strict_types=1);

namespace AssetOptimizer\Path;

use AssetOptimizer\Image\ImageOptimizer;
use AssetOptimizer\WatchMode;
use Symfony\Component\AssetMapper\Path\PublicAssetsFilesystemInterface;
use Symfony\Component\Filesystem\Filesystem;
use Throwable;
use function strlen;

/**
 * Decorates AssetMapper's public-assets filesystem to drop WebP and AVIF twins
 * next to each raster it writes: <name>.jpg -> <name>.jpg.webp / .jpg.avif
 * (extension appended).
 *
 * Living inside the write path means twins are generated by every compile,
 * however it was started (console command, programmatic, watch subprocess) —
 * no coupling to a command name. Incremental per format: an existing twin is
 * skipped (filenames are content hashes, so an existing twin means the content
 * is unchanged), so enabling a format later back-fills its twins without
 * re-encoding the other. A twin is only written when it is genuinely smaller
 * than what the server would otherwise pick: the raster for WebP; the raster
 * AND the on-disk WebP twin for AVIF, because the Accept rule prefers AVIF
 * when both exist. A candidate rejected as not-smaller leaves a zero-byte
 * `<twin>.skip` marker next to the raster, so the expensive encode is not
 * repeated on every (watch) compile — same content re-encodes to the same
 * bytes. Markers share the twins' lifecycle: content-hashed names, wiped with
 * public/assets.
 */
final readonly class TwinFilesystem implements PublicAssetsFilesystemInterface
{
    private Filesystem $fs;

    public function __construct(
        private PublicAssetsFilesystemInterface $inner,
        private ImageOptimizer                  $optimizer,
        private bool                            $debug,
        private bool                            $webpEnabled,
        private int                             $webpQuality,
        private bool                            $avifEnabled,
        private int                             $avifQuality,
    )
    {
        $this->fs = new Filesystem();
    }

    public function write(string $path, string $contents): void
    {
        $this->inner->write($path, $contents);
        $this->writeTwins($path, $contents);
    }

    public function copy(string $originPath, string $path): void
    {
        $this->inner->copy($originPath, $path);
        $this->writeTwins($path, null);
    }

    public function getDestinationPath(): string
    {
        return $this->inner->getDestinationPath();
    }

    /**
     * Encodes the twins from the just-written asset and drops each next to the
     * source when it is genuinely smaller than everything it competes with.
     *
     * @param ?string $contents the just-written bytes when the caller has them
     *                          (write); null makes copy stat the file instead
     */
    private function writeTwins(string $path, ?string $contents): void
    {
        if ((!$this->webpEnabled && !$this->avifEnabled) || 1 !== preg_match('/\.(jpe?g|png)$/i', $path)) {
            return;
        }

        // Mirror ImageOptimizeCompiler's dev gate: outside a watch compile,
        // dev writes raw rasters, and encoding twins of unoptimized bytes
        // would waste encoder work on files whose digests no watch preview
        // ever references.
        if ($this->debug && !WatchMode::active()) {
            return;
        }

        $local = $this->localPath($path);

        // $local is the exact raster the twins compete with and was just
        // written, so its size is available. If it can't be read, skip rather
        // than risk shipping a twin larger than its source.
        $sourceSize = null !== $contents ? strlen($contents) : @filesize($local);
        if (false === $sourceSize) {
            return;
        }

        // Each format is best-effort in isolation: the encode (incl. its GD
        // fallback), the size check, or the write may break the build, and a
        // failed format must not cost the other its twin. A missing twin is
        // fine; the Accept rule serves the next candidate instead.
        if ($this->webpEnabled) {
            try {
                $this->writeWebp($path, $local, $sourceSize);
            } catch (Throwable) {
                // leave the raster without a WebP twin
            }
        }

        if ($this->avifEnabled) {
            try {
                $this->writeAvif($path, $local, $sourceSize);
            } catch (Throwable) {
                // leave the raster without an AVIF twin
            }
        }
    }

    private function writeWebp(string $path, string $local, int $sourceSize): void
    {
        if ($this->fs->exists($local . '.webp') || $this->fs->exists($local . '.webp.skip')) {
            return; // content-hashed name → already converted (or rejected)
        }

        $webp = $this->optimizer->webp($local, $this->webpQuality);
        if (null === $webp) {
            return; // encoder unavailable — no marker, may become available
        }

        if (strlen($webp) < $sourceSize) {
            $this->inner->write($path . '.webp', $webp);
        } else {
            $this->markSkipped($path, '.webp');
        }
    }

    private function writeAvif(string $path, string $local, int $sourceSize): void
    {
        // The Accept rule prefers AVIF over WebP on existence alone, so the
        // AVIF twin must beat the raster AND whatever .webp sits on disk —
        // written by this pass, an earlier compile, or before WebP was
        // disabled. Unreadable size → skip conservatively, mirroring the
        // raster rule above.
        $webpSize = null;
        if ($this->fs->exists($local . '.webp')) {
            $webpSize = @filesize($local . '.webp');
            if (false === $webpSize) {
                return;
            }
        }

        if ($this->fs->exists($local . '.avif')) {
            // Re-validate: the twin may predate a back-filled smaller .webp
            // (it was bounded by the raster alone while WebP was disabled).
            // Re-encoding cannot help — same content, same bytes — so demote
            // it to a marker and let the Accept rule fall through to WebP.
            $avifSize = @filesize($local . '.avif');
            if (false === $avifSize || $avifSize >= $sourceSize || (null !== $webpSize && $avifSize >= $webpSize)) {
                $this->fs->remove($local . '.avif');
                $this->markSkipped($path, '.avif');
            }

            return;
        }

        if ($this->fs->exists($local . '.avif.skip')) {
            return; // rejected before: same content re-encodes to the same bytes
        }

        $avif = $this->optimizer->avif($local, $this->avifQuality);
        if (null === $avif) {
            return; // encoder unavailable — no marker, may become available
        }

        if (strlen($avif) < $sourceSize && (null === $webpSize || strlen($avif) < $webpSize)) {
            $this->inner->write($path . '.avif', $avif);
        } else {
            $this->markSkipped($path, '.avif');
        }
    }

    /**
     * Records "candidate rejected as not smaller" with a zero-byte marker, so
     * the encode is not repeated on every compile for a verdict that cannot
     * change while the content (hash) stays the same.
     */
    private function markSkipped(string $path, string $twinExt): void
    {
        $this->inner->write($path . $twinExt . '.skip', '');
    }

    private function localPath(string $path): string
    {
        return $this->inner->getDestinationPath() . '/' . ltrim($path, '/');
    }
}
