<?php

declare(strict_types=1);

namespace AssetOptimizer\Path;

use AssetOptimizer\Image\ImageOptimizer;
use Symfony\Component\AssetMapper\Path\PublicAssetsFilesystemInterface;
use function strlen;

/**
 * Decorates AssetMapper's public-assets filesystem to drop a WebP twin next to
 * each raster it writes: <name>.jpg -> <name>.jpg.webp (extension appended).
 *
 * Living inside the write path means twins are generated by every compile,
 * however it was started (console command, programmatic, watch subprocess) —
 * no coupling to a command name. Incremental: skips twins that already exist
 * (filenames are content hashes, so an existing twin means the content is
 * unchanged) and any twin that would not be smaller than its source.
 */
final readonly class WebpTwinFilesystem implements PublicAssetsFilesystemInterface
{
    public function __construct(
        private PublicAssetsFilesystemInterface $inner,
        private ImageOptimizer                  $optimizer,
        private bool                            $enabled,
        private int                             $quality,
    )
    {
    }

    public function write(string $path, string $contents): void
    {
        $this->inner->write($path, $contents);
        $this->writeTwin($path, strlen($contents));
    }

    public function copy(string $originPath, string $path): void
    {
        $this->inner->copy($originPath, $path);
        $this->writeTwin($path, @filesize($originPath));
    }

    public function getDestinationPath(): string
    {
        return $this->inner->getDestinationPath();
    }

    /**
     * Encodes a WebP twin from the just-written asset and drops it next to the
     * source when it is genuinely smaller. $sourceSize is the size of the asset
     * the twin would replace; `false` (size unknown) skips the size guard rather
     * than discarding an otherwise valid twin.
     */
    private function writeTwin(string $path, int|false $sourceSize): void
    {
        if (!$this->wantsTwin($path)) {
            return;
        }

        $webp = $this->optimizer->webp($this->localPath($path), $this->quality);
        if (null === $webp || '' === $webp) {
            return;
        }
        if (false !== $sourceSize && strlen($webp) >= $sourceSize) {
            return;
        }

        $this->inner->write($path . '.webp', $webp);
    }

    private function wantsTwin(string $path): bool
    {
        return $this->enabled
            && 1 === preg_match('/\.(jpe?g|png)$/i', $path)
            && !is_file($this->localPath($path) . '.webp');
    }

    private function localPath(string $path): string
    {
        return $this->inner->getDestinationPath() . '/' . ltrim($path, '/');
    }
}
