<?php

declare(strict_types=1);

namespace AssetOptimizer\Path;

use AssetOptimizer\Image\ImageOptimizer;
use AssetOptimizer\Watch\WatchLock;
use Symfony\Component\AssetMapper\Path\PublicAssetsFilesystemInterface;
use Symfony\Component\Filesystem\Filesystem;
use Throwable;
use function strlen;

/**
 * Decorates AssetMapper's public-assets filesystem to drop a WebP twin next to
 * each raster it writes: <name>.jpg -> <name>.jpg.webp (extension appended).
 *
 * Living inside the write path means twins are generated by every compile,
 * however it was started (console command, programmatic, watch subprocess) —
 * no coupling to a command name. Incremental: skips twins that already exist
 * (filenames are content hashes, so an existing twin means the content is
 * unchanged) and any twin that would not be smaller than its source.
 */
final readonly class WebpTwinFilesystem implements PublicAssetsFilesystemInterface
{
    private Filesystem $fs;

    public function __construct(
        private PublicAssetsFilesystemInterface $inner,
        private ImageOptimizer                  $optimizer,
        private WatchLock                       $watchLock,
        private bool                            $debug,
        private bool                            $enabled,
        private int                             $quality,
    )
    {
        $this->fs = new Filesystem();
    }

    public function write(string $path, string $contents): void
    {
        $this->inner->write($path, $contents);
        $this->writeTwin($path);
    }

    public function copy(string $originPath, string $path): void
    {
        $this->inner->copy($originPath, $path);
        $this->writeTwin($path);
    }

    public function getDestinationPath(): string
    {
        return $this->inner->getDestinationPath();
    }

    /**
     * Encodes a WebP twin from the just-written asset and drops it next to the
     * source when it is genuinely smaller than the raster it would replace.
     */
    private function writeTwin(string $path): void
    {
        if (!$this->enabled || 1 !== preg_match('/\.(jpe?g|png)$/i', $path)) {
            return;
        }

        // Mirror ImageOptimizeCompiler's dev gate: without a watch, dev writes
        // raw rasters, and encoding twins of unoptimized bytes would waste
        // cwebp work on files whose digests no watch preview ever references.
        if ($this->debug && !$this->watchLock->isHeld()) {
            return;
        }

        $local = $this->localPath($path);
        if ($this->fs->exists($local . '.webp')) {
            return; // content-hashed name → already converted
        }

        // Serialize twin generation for this exact raster across concurrent
        // compiles (a watch subprocess and a manual `asset-map:compile` can both
        // reach here for the same asset): an advisory lock on the source file
        // lets only one process run the expensive cwebp `-m 6` encode; the loser
        // skips and the winner produces the twin. flock is released when the fd
        // closes — including on process death — so the lock can never go stale,
        // unlike a lock file. If the file can't be opened we proceed unlocked
        // (best-effort: at worst two processes encode, which is only wasted CPU).
        $lock = @fopen($local, 'r');
        if (false !== $lock && !flock($lock, LOCK_EX | LOCK_NB)) {
            fclose($lock);

            return;
        }

        // Best-effort: nothing here — the encode (incl. its GD fallback), the
        // size check, or the write — may break the build. A missing twin is
        // fine; the Accept rule serves the raster instead.
        try {
            // Re-check under the lock: the winner may have finished between the
            // exists() above and acquiring the lock.
            if ($this->fs->exists($local . '.webp')) {
                return;
            }
            $webp = $this->optimizer->webp($local, $this->quality);
            if (null === $webp) {
                return;
            }
            // $local is the exact raster the twin competes with and was just
            // written, so its size is available. Only write a genuinely smaller
            // twin; if the size can't be read, skip rather than risk shipping a
            // .webp larger than its source.
            $sourceSize = @filesize($local);
            if (false === $sourceSize || strlen($webp) >= $sourceSize) {
                return;
            }
            $this->inner->write($path . '.webp', $webp);
        } catch (Throwable) {
            // leave the raster without a twin; the Accept rule falls back to it
        } finally {
            if (false !== $lock) {
                flock($lock, LOCK_UN);
                fclose($lock);
            }
        }
    }

    private function localPath(string $path): string
    {
        return $this->inner->getDestinationPath() . '/' . ltrim($path, '/');
    }
}
