<?php

declare(strict_types=1);

namespace AssetOptimizer\Path;

use AssetOptimizer\Image\ImageOptimizer;
use Symfony\Component\AssetMapper\Path\PublicAssetsFilesystemInterface;
use Throwable;
use function strlen;

/**
 * Decorates AssetMapper's public-assets filesystem to drop a WebP twin next to
 * each raster it writes: <name>.jpg -> <name>.jpg.webp (extension appended).
 *
 * Living inside the write path means twins are generated by every compile,
 * however it was started (console command, programmatic, watch subprocess) —
 * no coupling to a command name. Incremental: skips twins that already exist
 * (filenames are content hashes, so an existing twin means the content is
 * unchanged) and any twin that would not be smaller than its source.
 */
final readonly class WebpTwinFilesystem implements PublicAssetsFilesystemInterface
{
    public function __construct(
        private PublicAssetsFilesystemInterface $inner,
        private ImageOptimizer                  $optimizer,
        private bool                            $enabled,
        private int                             $quality,
    )
    {
    }

    public function write(string $path, string $contents): void
    {
        $this->inner->write($path, $contents);
        $this->writeTwin($path);
    }

    public function copy(string $originPath, string $path): void
    {
        $this->inner->copy($originPath, $path);
        $this->writeTwin($path);
    }

    public function getDestinationPath(): string
    {
        return $this->inner->getDestinationPath();
    }

    /**
     * Encodes a WebP twin from the just-written asset and drops it next to the
     * source when it is genuinely smaller than the raster it would replace.
     */
    private function writeTwin(string $path): void
    {
        if (!$this->enabled || 1 !== preg_match('/\.(jpe?g|png)$/i', $path)) {
            return;
        }

        $local = $this->localPath($path);
        if (is_file($local . '.webp')) {
            return; // content-hashed name → already converted
        }

        // Best-effort: nothing here — the encode (incl. its GD fallback), the
        // size check, or the write — may break the build. A missing twin is
        // fine; the Accept rule serves the raster instead.
        try {
            $webp = $this->optimizer->webp($local, $this->quality);
            if (null === $webp) {
                return;
            }
            // $local is the exact raster the twin competes with and was just
            // written, so its size is available. Only write a genuinely smaller
            // twin; if the size can't be read, skip rather than risk shipping a
            // .webp larger than its source.
            $sourceSize = @filesize($local);
            if (false === $sourceSize || strlen($webp) >= $sourceSize) {
                return;
            }
            $this->inner->write($path . '.webp', $webp);
        } catch (Throwable) {
            // leave the raster without a twin; the Accept rule falls back to it
        }
    }

    private function localPath(string $path): string
    {
        return $this->inner->getDestinationPath() . '/' . ltrim($path, '/');
    }
}
